typography_spectrum: 0.18564523034729064
color:
  brandStrength: 0.154240160016343
  lightness: 0.10820031282491982
  saturation: 0.8897647224366665
  rhythmicContrast: 0.3168975533917546
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
opengraph:
  image: null
layout_spectrum: 0.5543544143438339
author:
  name: Philipp Schmalen
  email: philippschmalen@gmail.com
name: Volles Korn voraus
title: Von Vollkorn und Fliegen
description: 'Hongkong hat eine millionen mal mehr Menschen, als meine WG'
